# Generated by Django 2.2 on 2019-06-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='scheme',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
