# Generated by Django 2.2 on 2019-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190616_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='for_date',
            field=models.DateField(blank=True),
        ),
    ]
